name: sic_dmd
channels:
  - conda-forge
#  - defaults
dependencies:
  - python=3.11
  - numpy>2.0
  - scipy
  - matplotlib
  - tqdm
  - dill
  - pip
  - xarray
  - pandas
  - seaborn
  - h5py
  - pip:
    - pydmd
